### PR TITLE
adding the property density feature to the EPC dataset

### LINKED ISSUE #42: Add number of households, land area and property density feature to EPC dataset
Enhance EPC dataset with the households, land area and property density feature!

### PR DESCRIPTION
**Pull request by helloaidank**
---

# Description
This is a PR which adds the number of households, the land area and the property density per LSOA as features for England and Wales to the EPC dataset

Fixes #42 

# Instructions for Reviewer
I've made changes to / added the following files (if you could quickly go through them and check to see if everything seems OK):
- `pipeline/run_scripts/add_features.py`
- `pipeline/prepare_features/number_of_households.py`
- `pipeline/prepare_features/property_density.py`
- `pipeline/prepare_features/output_areas.py`
- `getters/get_datasets.py`
- `config/base.yaml`

In order to test the code in this PR you need to run the following:
`python pipeline/run_scripts/add_features.py --epc_path "s3://asf-heat-pump-suitability/outputs/2023_Q2_EPC_enhanced_weights_sample_10k.parquet" --save_output "s3://asf-heat-pump-suitability/outputs/2023_Q2_EPC_enhanced_weights_property_density_sample_test_10k.parquet"`

Please pay special attention to any bugs, sense test the functions and please think of any efficiencies that can be made and sense check the outputs!

# Checklist:

- [ ] I have refactored my code out from `notebooks/`
- [X] I have checked the code runs
- [ ] I have tested the code
- [X] I have run `pre-commit` and addressed any issues not automatically fixed
- [ ] I have merged any new changes from `dev`
- [X] I have documented the code
  - [X] Major functions have docstrings
  - [ ] Appropriate information has been added to `README`s
- [X] I have explained this PR above
- [X] I have requested a code review

### CODE REVIEW

**Comment by lizgzil** [comment]
Thanks so much for this @helloaidank 🎉 .  I ran out of time to review it fully though :(

I read over it - and it looks good to me. I also ran the code and it worked, the resulting dataset seemed to be the correct shape.

The thing I'd like to investigate more is the values. I noticed that the max households per km2 was over 60,000 - This value is for an LSOA 'E01034147' in Croydon which only has one EPC value and I can see on street view that this area has a lot of big flats, so I guess it might make sense? According to a quick google the density of London is 5640 people per km2.  Anyway, the code looks good, but I think @crispy-wonton could do with checking it too since I was a bit rushed!

**Comment by helloaidank** [comment]
> Thanks so much for this @helloaidank 🎉 . I ran out of time to review it fully though :(
> 
> I read over it - and it looks good to me. I also ran the code and it worked, the resulting dataset seemed to be the correct shape.
> 
> The thing I'd like to investigate more is the values. I noticed that the max households per km2 was over 60,000 - This value is for an LSOA 'E01034147' in Croydon which only has one EPC value and I can see on street view that this area has a lot of big flats, so I guess it might make sense? According to a quick google the density of London is 5640 people per km2. Anyway, the code looks good, but I think @crispy-wonton could do with checking it too since I was a bit rushed!

Thanks Liz for reviewing it! 

That specific LSOA seems to have a very tall apartment block (Pinnacle, 44 floors and is apparently the 60th tallest building in the UK) and the area is tiny in comparison to other LSOAs (0.0097 km^{2}), so I think on initial viewing the property density is not too surprising?

**Review by lizgzil — APPROVED** [review]
thanks Aidan! I checked a few of the MSOAs with the most and least average population density and they all seemed to make sense.

**Comment by helloaidank** [comment]
Great, I've merged this branch now! I'll pull out some high level statistics and potentially a distribution but I'll move on with the other PRs now.

**Pull request merged**
